### ISSUE TITLE
Spam score column not longer available in Thunderbird 115

### ISSUE THREAD

**Issue by digitaldutch** [friedPotat0/Spam-Scores#59] opened 2023-07-12 15:47 UTC
**Describe the bug**
Spam score column not longer available in Thunderbird 115. There were GUI changes in Thunderbird 115. I guess it broke the column feature. The button in the message area still works fine.

**Reproduction steps**
Right click the column headers and the spam score option is no longer available

**Expected behavior**
The spam score column should be available

**Thunderbird (please complete the following information):**
 - Windows 11

**Spam Score add-on (please complete the following information):**
 - Version: 1.4.1

**Comment by ValentinDrean** [comment] 2023-07-23 13:10
I can confirm this here on TB `115.0.1 (64-bit)` from `EndeavourOS Linux 6.4.4-zen1-1-zen`

**Comment by friedPotat0** [comment] 2023-07-24 11:52
Thank you for reporting the problem. Since I also use Thunderbird 115 myself, I will take a look at the problem in the next few weeks. Unfortunately, I don't have much time for the project at the moment.

**Comment by digitaldutch** [comment] 2023-07-30 09:14
Did some reading: It is not possible to add custom columns to the new treeview in Thunderbird 115.

[Bug report: No way for extensions to add columns to the new tree list widgets](https://bugzilla.mozilla.org/show_bug.cgi?id=1817682)

Work is started on an API to reenable it:
[WIP: Bug 1817682 - Functions for extensions to add custom column handlers.](https://phabricator.services.mozilla.com/D179632)

**Comment by PitWenkin** [comment] 2023-10-06 11:21
I can confirm it's no longer working on Thunderbird `115.3.1 (64-bit)` on `macOS 13.6`

The last last few Thunderbird updates were half-arsed themselves, so please don't feel bad that your add-on no longer works.

**Comment by RalfRoemling** [comment] 2023-10-11 17:12
Hi @friedPotat0 .
thx a lot for your great plugin. I looove it 🥇 

Sadly TB forced their update to 115.x now. Any idea when you may be able to update SpamScores?

Elsewise I'll downgrade to the previous version, I guess.

**Comment by RalfRoemling** [comment] 2023-10-12 06:49
You're welcome, and yes sad indeed. Will go back to 102 until the change @digitaldutch mentioned will be inocorporated. Does anybody know where I can leave a comment to help press the urge vor implementation?

**Comment by RalfRoemling** [comment] 2024-02-14 11:39
TB-team is movin' forward I think. According to this https://bugzilla.mozilla.org/show_bug.cgi?id=1615801 they re-implement the column-api for beta-testing on Feb 19th?

**Comment by RalfRoemling** [comment] 2024-06-15 08:30
Been a long time, and I just took another look on the state of affairs. As far as I understand it final re-implementation of the API is postponed after TB128, but experimental use is ongoing. @friedPotat0 any way you may join the train?

**Comment by vali-um** [comment] 2024-06-18 12:05
Thanks for this plugin, even without the column it is still very useful on TB115.
It would be great if the manifest allowed installation anyways even if the column doesn't work... (did this manually for my personal installation, but its not feasible to recommend this to others...)
We'd like to do some work on the column re-implementation but with the experimental API i'm unsure if its worth while to put in the work now...

**Comment by PitWenkin** [comment] 2024-06-18 13:07
> even without the column it is still very useful on TB115.

Indeed …

>It would be great if the manifest allowed installation anyways even if the column doesn't work... (did this manually for my personal installation, but its not feasible to recommend this to others...)

I would be more than happy if you could share a how-to … or a fork witout the column implementation?

**Comment by de-es** [comment] 2024-06-18 13:24
.xpi is just a zip file. Extract `manifest.json`, edit `strict_max_version` to `115.*`, update the file in the zip archive (or repack) and (re-)install.

**Comment by vali-um** [comment] 2024-06-18 13:32
I just created an alpha branch in my fork of the plugin which contains my pull requests #62 and #61 and the required changes to manifest.json
If you build the plugin from https://github.com/vali-um/Spam-Scores/tree/alpha you get a plugin version 1.4.2-alpha1 you can install

**Comment by PitWenkin** [comment] 2024-06-18 18:58
Unfortunately nomatter what I try, I can neither change the manifest of the official `.xpi` nor can I create a `xpi` of @vali-um's version, which is accepted by my thunderbird … either thunderbird tells me the file is corrupt or not compatible with `115.1.1` …

**Comment by thomas-maeder** [comment] 2024-06-20 08:42
Thanks for v1.4.2!
No column yet, but a big step in the right direction!

**Comment by vali-um** [comment] 2024-06-20 10:11
@friedPotat0 Thanks for the release, didn't know that the addon store requires this flag.

Are you planning to work on the column feature with the experimental interface on TB115 or TB128?
We are thinking about putting in some work but i wouldn't want to work on something you already have prepared.

**Comment by friedPotat0** [comment] 2024-06-20 10:24
At the moment I don't have the time to test any experimental interface and I have not implemented anything so far. But of course I would be extremely happy if you could invest more of your time in the project.

Please let me know if you need any help or additional information.

**Comment by friedPotat0** [comment] 2024-06-21 07:14
The Thunderbird Team recommended the following example add-ons that already use the new custom column API: https://thunderbird.topicbox.com/groups/addons/Tf7f2d663f8314b02-M331579b0c86d57b4d9d95b41/proposal-custom-column-api-for-message-list

**Comment by jobisoft** [comment] 2024-07-23 23:01
Proposed re-implementation of custom columns in #63

**Comment by friedPotat0** [comment] 2024-07-24 09:47
Thank you so much for your help! Everything worked perfcectly during my review. 💯🎉

**Comment by friedPotat0** [comment] 2024-07-24 10:32
The new version v1.5.0, including this change, is now available in the Thunderbird add-on store and on the releases page (https://github.com/friedPotat0/Spam-Scores/releases/tag/1.5.0).

**Closed by friedPotat0** 2024-07-24 10:32 UTC
Labels: bug

**Comment by RalfRoemling** [comment] 2024-07-26 15:09
Thx a lot for the good work! Much appreciated. Have a great weekend! 👋 🍻

**Comment by PitWenkin** [comment] 2024-07-30 11:41
FYI after updating to TB 128 the plugin still works
